openapi: 3.0.0
info:
  version: 1.0.0
  title: Tweeter API
paths:
  /v1/users:
    post:
      tags:
        - Users
      summary: Create User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error

  /v1/users/login:
    post:
      tags:
        - Users
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSuccessResponse'
        '400':
          description: Invalid email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthErrorResponse'
        '500':
          description: Internal Server Error

  /v1/users/logout:
    post:
      tags:
        - Users
      summary: User Logout
      responses:
        '200':
          description: Logged out successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
        '500':
          description: Internal Server Error

  /v1/users/{id}:
    get:
      tags:
        - Users
      summary: Get Current User Profile
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Current User Profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '500':
          description: Internal Server Error

  /v1/users:
    patch:
      tags:
        - Users
      summary: Edit User Profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserProfile'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /v1/tweets:
    post:
      tags:
        - Tweets
      summary: Create Tweet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTweetRequest'
      responses:
        '200':
          description: Tweet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tweet'
        '400':
          description: Invalid tweet data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error

    patch:
      tags:
        - Tweets
      summary: Edit Tweet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTweetRequest'
      responses:
        '200':
          description: Tweet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tweet'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        password:
          type: string
        email:
          type: string
        emailToken:
          type: string
        confirmEmailToken:
          type: boolean
        resetPasswordToken:
          type: string
        birthDate:
          type: string
        nickname:
          type: string
        bio:
          type: string
        location:
          type: string
        tweet:
          type: object
        following:
          type: array
          items:
            type: integer
        followers:
          type: array
          items:
            type: integer

    UserLoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    AuthSuccessResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string

    AuthErrorResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string

    LogoutResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string

    UserProfile:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        birthdate:
          type: string
        bio:
          type: string
        location:
          type: string
        nickname:
          type: string

    UpdateUserProfile:
      type: object
      properties:
        name:
          type: string
        nickname:
          type: string
        birthdate:
          type: string
        email:
          type: string
        password:
          type: string

    CreateTweetRequest:
      type: object
      properties:
        userID:
          type: integer
        author:
          type: string
        text:
          type: string
        createdAt:
          type: string
          format: date-time

    UpdateTweetRequest:
      type: object
      properties:
        tweetID:
          type: integer
        text:
          type: string

    Tweet:
      type: object
      properties:
        tweetID:
          type: integer
        userID:
          type: integer
        author:
          type: string
        text:
          type: string
        createdAt:
          type: string
          format: date-time
